export CLOUD=aws
export ENVIRONMENT=prod
export NUMBER_INSTANCES=2
export REPORT_AREA=
export REPORT_PROJECT=

export NETWORK_NAME=
export NETWORK_PROJECT_ID=
export SUBNETWORK_NAME=
export EXTERNAL_NETWORK=
export PROVISIONING_MODEL=

export REGION=
export ZONE=
export MACHINE_TYPE=t3.micro
export PROJECT_ID=glive

export SERVICE_ACCOUNT=
export GCP_SERVICE_ACCOUNT_FILE=

export AWS_ACCESS_KEY=
export AWS_SECRET_KEY=
