save_config(){

cat > "$CONFIG_FILE" <<EOF
export CLOUD=$CLOUD
export ENVIRONMENT=$ENVIRONMENT
export NUMBER_INSTANCES=$NUMBER_INSTANCES
export REPORT_AREA=$REPORT_AREA
export REPORT_PROJECT=$REPORT_PROJECT

export NETWORK_NAME=$NETWORK_NAME
export NETWORK_PROJECT_ID=$NETWORK_PROJECT_ID
export SUBNETWORK_NAME=$SUBNETWORK_NAME
export EXTERNAL_NETWORK=$EXTERNAL_NETWORK
export PROVISIONING_MODEL=$PROVISIONING_MODEL

export REGION=$REGION
export ZONE=$ZONE
export MACHINE_TYPE=$MACHINE_TYPE
export PROJECT_ID=$PROJECT_ID

export SERVICE_ACCOUNT=$SERVICE_ACCOUNT
export GCP_SERVICE_ACCOUNT_FILE=$GCP_SERVICE_ACCOUNT_FILE

export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
export AWS_SECRET_KEY=$AWS_SECRET_KEY
EOF

echo "Configuração salva em $CONFIG_FILE"

}