---
- name: Executa o terraform init K6 na AWS
  when:  k6_instances_cloud_provider == "aws"
  become: false
  shell: 'cd ../../terraform/aws/{{ lookup("env", "PROJECT_ID") }} && terraform init'
  delegate_to: 127.0.0.1
- name: Executa o terraform destroy K6 na AWS
  when:  k6_instances_cloud_provider == "aws"
  become: false
  shell: 'cd ../../terraform/aws/{{ lookup("env", "PROJECT_ID") }} && terraform destroy --auto-approve'
  delegate_to: 127.0.0.1
- name: Executa o terraform init K6 na GCP
  shell: 'cd ../../terraform/gcp/{{ lookup("env", "PROJECT_ID") }} && terraform init'
  when:  k6_instances_cloud_provider == "gcp"
- name: Executa o terraform destroy K6 na GCP
  shell: 'cd ../../terraform/gcp/{{ lookup("env", "PROJECT_ID") }} && terraform destroy --auto-approve'
  when:  k6_instances_cloud_provider == "gcp"