plugin: aws_ec2
aws_access_key: 
aws_secret_key: 
regions:
  - us-east-1
keyed_groups:
  - key: tags
    prefix: tag
groups:
  k6_instances:
    include:
      - '*k6*'
compose:
  ansible_host: private_ip_address
