plugin: aws_ec2
aws_access_key: ###AWS_ACCESS_KEY###
aws_secret_key: ###AWS_SECRET_KEY###
regions:
  - ###REGION###
keyed_groups:
  - key: tags
    prefix: tag
groups:
  k6_instances:
    include:
      - '*k6*'
compose:
  ansible_host: private_ip_address