plugin: aws_ec2
aws_access_key: AKIAUKRMVKHG2R27FGER
aws_secret_key: 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
regions:
  - us-east-1
keyed_groups:
  - key: tags
    prefix: tag
groups:
  k6_instances:
    include:
      - '*k6*'
compose:
  ansible_host: private_ip_address
