{
 "title": "K6 Load Testing Results",
 "description": "k6.io load tests results",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "url", "label": "url", "query": { "query": "label_values(url)" } },
   { "name": "scenario", "query": { "query": "label_values(scenario)" } },
   { "name": "method", "query": { "query": "label_values(method)" } }
  ]
 },
 "panels": [
  { "title": "Global metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Iterations per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations[$__rate_interval]))",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(k6_data_sent[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count by (url) (k6_http_reqs{scenario=\"$scenario\",method=~\"$method\"})",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "% Failed Checks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_check{outcome=\"fail\"}[$__rate_interval])) / sum(rate(k6_check[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_script_errors[$__rate_interval]))",
     "legendFormat": "Script errors"
    }
   ]
  },
  { "title": "K6 HTTP Request: ${url}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "K6RequestName" },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs{url=~\"$url\"}[$__rate_interval])) by(status, url)",
     "legendFormat": "{{url}} - {{status}}"
    }
   ]
  },
  {
   "title": "Response time (95th)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_p95{url=~\"$url\",expected_response=\"true\"})",
     "legendFormat": "Successful responses"
    },
    {
     "expr": "avg(k6_http_req_duration_p95{url=~\"$url\",expected_response=\"false\"})",
     "legendFormat": "Failed responses"
    }
   ]
  },
  {
   "title": "Response time (avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_avg{url=~\"$url\",expected_response=\"true\"})",
     "legendFormat": "Successful responses"
    },
    {
     "expr": "avg(k6_http_req_duration_avg{url=~\"$url\",expected_response=\"false\"})",
     "legendFormat": "Failed responses"
    }
   ]
  },
  {
   "title": "HTTP breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(k6_http_req_blocked_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(k6_http_req_waiting_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(k6_http_req_ending_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
     "legendFormat": "Sending"
    },
    {
     "expr": "sum(k6_http_req_receiving_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
     "legendFormat": "Receiving"
    },
    {
     "expr": "sum(k6_http_tls_handshaking_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
     "legendFormat": "TLS handshaking"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(k6_http_req_duration_avg{url=~\"$url\"}) by(status, url)",
     "legendFormat": "{{url}} - {{status}}"
    }
   ]
  }
 ]
}