TERRAFORM_PATH="infra/terraform"
ANSIBLE_PATH="infra/ansible"
CONFIG_FILE=".config.sh"
PROXY_GCP_SA="http://proxy-sa-e1.gcp.i.globo:3128"
PROXY_GCP_E1="http://proxy-us-e1.gcp.i.globo:3128"
NO_PROXY_HOSTS="localhost,127.0.0.1,10.,.globoi.com,i.s3.glbimg.com,.googleapis.com,.apps.g.globo,.apps.tsuru.dev.gcp.i.globo,.globo.com,.apps.tsuru.gcp.i.globo"
GITLAB_URL="gitlab@gitlab.globoi.com"
K6_PREFFIX="/tmp/k6_results"
K6_TEMP="k6-temp"
K6_SCRIPTS="/tmp/k6-performance-tests/"
K6_CMD_COMMOM="/usr/local/sbin/k6"
K6_SUMMARY="--summary-export /tmp/k6_results"
REPORT_URL="https://qacreport-api.sre.hdg.hub.gcp.i.globo/taas"
INFRACOST_CREDENTIALS="$HOME/.config/infracost/credentials.yml"
LOG_DIR="logs"
CMD_COMMON="sudo -u root bash -c 'cd ${K6_SCRIPTS} ; export NO_PROXY=\"${NO_PROXY_HOSTS}\" ; "